import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { WithApollo } from "./providers/with-apollo";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <WithApollo>
        <body className={inter.className}>{children}</body>
      </WithApollo>
    </html>
  );
}
export default RootLayout